# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15  # 최신 macOS (Sequoia)
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Xcode version
      run: xcodebuild -version

    - name: List available simulators
      run: xcrun simctl list devices available

    - name: Show available destinations
      run: xcodebuild -scheme ComfortableMove -project ComfortableMove/ComfortableMove.xcodeproj -showdestinations

    - name: Build
      run: |
        xcodebuild clean build \
        -project ComfortableMove/ComfortableMove.xcodeproj \
        -scheme ComfortableMove \
        -destination 'platform=iOS Simulator,name=iPhone 16' \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO
